### ISSUE TITLE
cannot add worker nodes

### ISSUE THREAD

**Issue by julian-siebert** [hcloud-k8s/terraform-hcloud-kubernetes#33]
Cannot increase count of worker nodes. It drops follwing error:

module.hcloud-k8s.hcloud_server.worker["prod-worker-cx22-nbg-1"]: Creating...
╷
│ Error: error during placement (resource_unavailable, de76d43fd51bd20)
│ 
│   with module.hcloud-k8s.hcloud_server.worker["prod-worker-cx22-nbg-1"],
│   on .terraform/modules/hcloud-k8s/server.tf line 69, in resource "hcloud_server" "worker":
│   69: resource "hcloud_server" "worker" {
│ 
╵

**Comment by julian-siebert** [comment]
what does that mean?

**Comment by M4t7e** [comment]
`resource_unavailable` indicates that the requested resource (CX22 in Nuremberg) is temporarily unavailable. For details, check: https://status.hetzner.com/incident/aa5ce33b-faa5-4fd0-9782-fde43cd270cf
![image](https://github.com/user-attachments/assets/29371c45-c000-45cd-8f29-3c57c23a42c5)

Typically, an info banner is displayed after logging into the Hetzner Console, and the affected server type will be greyed out in the GUI when attempting to create it in the same region where the Terraform operation failed.
