### ISSUE TITLE
Support for Auto scaling

### ISSUE THREAD

**Issue by lpellegr** [hcloud-k8s/terraform-hcloud-kubernetes#4]
Your project looks very promising. Unfortunately, I was looking for a way to add auto scaling agent nodes. Any plan to add such support?

**Comment by laurentpellegrino** [comment]
OMG, I did not notice the Advanced section. It seems you already support auto scaling! I will give a try immediately.

**Comment by M4t7e** [comment]
Yes, it is supported. Unfortunately there is still the https://github.com/kubernetes/autoscaler/issues/7210 bug. Let me fix that quickly...

Right now this project is under heavy development and there might come a breaking change in 0.* releases. But I'm almost done and just working on Longhorn integration as last component on my to do list. After that, it'll be hopefully stable with only backwards compatible changes.

**Comment by laurentpellegrino** [comment]
Thank you so much for all the hard work on this. The use of Talos looks fantastic.

Up until now, I’d been using https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner, but the current version is completely broken, and unfortunately, my live cluster went down today as well. I'm giving your project a try right now.

**Comment by laurentpellegrino** [comment]
@M4t7e Is there a way to pass the autoscaler some options. Something like:

```
  cluster_autoscaler_extra_args = [
    "--scale-down-delay-after-add=45m",
    "--scale-down-delay-after-delete=4m",
    "--scale-down-unneeded-time=5m"
  ]
```

**Comment by M4t7e** [comment]
The bug should be fixed in [0.2.1](https://github.com/hcloud-k8s/terraform-hcloud-kubernetes/releases/tag/0.2.1). I just tested it and the Autoscaler works now without errors.

> Up until now, I’d been using https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner, but the current version is completely broken, and unfortunately, my live cluster went down today as well. I'm giving your project a try right now.

I'm familiar with that project as I am part of the core team and have mainly contributed to the networking and security aspects. It is a very nice and popular project and can totally recommend that in general.

For our business, we require a cluster that is completely reliable and reproducible, with no automatic upgrades or other surprises running in the background. Additionally, I have not found any Kubernetes project for Hcloud that adequately manages the versioning of all its components. This project will not be maintenance free, but hopefully very stable and predictable for production workloads.

**Comment by laurentpellegrino** [comment]
Thanks. I just did a try with version 0.2.1 but without success (https://github.com/hcloud-k8s/terraform-hcloud-kubernetes/issues/5). To be honest, I don't have experience with terraform and just try to follow the docs in the README.

**Comment by M4t7e** [comment]
> @M4t7e Is there a way to pass the autoscaler some options. Something like:
> 
> ```
>   cluster_autoscaler_extra_args = [
>     "--scale-down-delay-after-add=45m",
>     "--scale-down-delay-after-delete=4m",
>     "--scale-down-unneeded-time=5m"
>   ]
> ```

I've just added support for this in version [0.3.0](https://github.com/hcloud-k8s/terraform-hcloud-kubernetes/releases/tag/0.3.0). You can find the updated documentation in the [README](https://github.com/hcloud-k8s/terraform-hcloud-kubernetes?tab=readme-ov-file#hammer_and_pick-advanced-configuration). Please note that the variable name has changed from `autoscaler_nodepools` to `cluster_autoscaler_nodepools`.

**Comment by laurentpellegrino** [comment]
Incredible! I will give it a try. Thanks a lot.

**Comment by M4t7e** [comment]
The variable `cluster_autoscaler_extra_args` has been renamed to `cluster_autoscaler_helm_values`. This naming and functionality have been extended to all Helm-based components, allowing for the merging and overwriting of existing values with the provided ones, similar to using [multiple Helm values files](https://helm.sh/docs/helm/helm_install/#synopsis) via the Helm CLI.
