### ISSUE TITLE
Error: name is already used

### ISSUE THREAD

**Issue by lpellegr** [hcloud-k8s/terraform-hcloud-kubernetes#5]
I am trying to deploy a cluster with autoscaling nodes. Here is the configuration used:

```
module "kubernetes" {
  source  = "hcloud-k8s/kubernetes/hcloud"
  version = "0.2.1"

  cluster_name = "github-runners"
  hcloud_token = "xxx"

  # Export configs for Talos and Kube API access
  cluster_kubeconfig_path  = "kubeconfig"
  cluster_talosconfig_path = "talosconfig"

  # Optional Ingress Controller and Cert Manager
  cert_manager_enabled  = true
  ingress_nginx_enabled = false

  control_plane_nodepools = [
    { name = "control-fsn", type = "cx22", location = "fsn1", count = 3 }
  ]

  autoscaler_nodepools = [
    {
      name     = "test-cax31"
      type     = "cax31"
      location = "hel1"
      min      = 0
      max      = 1
      labels   = { "autoscaler-node" = "true", "test/nodepool": "cax31" }
      taints   = [ "autoscaler-node=true:NoExecute", "github.com/runners=only:NoSchedule" ]
    }
  ]

}
```

Upon `terraform apply`, I am getting this error:

> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> module.kubernetes.hcloud_ssh_key.this: Creating...
> module.kubernetes.hcloud_network.this[0]: Creating...
> module.kubernetes.hcloud_placement_group.control_plane: Creating...
> module.kubernetes.hcloud_firewall.this: Creating...
> ╷
> │ Error: name is already used (uniqueness_error, 798f68ce15f02ac7)
> │ 
> │   with module.kubernetes.hcloud_firewall.this,
> │   on .terraform/modules/kubernetes/firewall.tf line 95, in resource "hcloud_firewall" "this":
> │   95: resource "hcloud_firewall" "this" {
> │ 
> ╵
> ╷
> │ Error: name is already used (uniqueness_error, c73a93df20a4149d3f490f0c081555ed)
> │ 
> │   with module.kubernetes.hcloud_network.this[0],
> │   on .terraform/modules/kubernetes/network.tf line 63, in resource "hcloud_network" "this":
> │   63: resource "hcloud_network" "this" {
> │ 
> ╵
> ╷
> │ Error: name is already used (uniqueness_error, 10f02096105285cc)
> │ 
> │   with module.kubernetes.hcloud_placement_group.control_plane,
> │   on .terraform/modules/kubernetes/placement_group.tf line 1, in resource "hcloud_placement_group" "control_plane":
> │    1: resource "hcloud_placement_group" "control_plane" {
> │ 
> ╵
> ╷
> │ Error: API request failed
> │ 
> │   with module.kubernetes.hcloud_ssh_key.this,
> │   on .terraform/modules/kubernetes/ssh_key.tf line 5, in resource "hcloud_ssh_key" "this":
> │    5: resource "hcloud_ssh_key" "this" {
> │ 
> │ An unexpected error was encountered during an API request.
> │ 
> │ SSH key name is already used
> │ 
> │ Error code: uniqueness_error
> │ Status code: 409

Any idea what's wrong?

**Comment by M4t7e** [comment]
Your Hetzner project appears to have an existing deployment, or you might be attempting a second deployment from a different directory. To make updates, use the directory containing the `terraform.tfstate` file from the initial deployment. Alternatively, if you wish to start anew, first [tear down](https://github.com/hcloud-k8s/terraform-hcloud-kubernetes?tab=readme-ov-file#boom-teardown) the existing cluster.

**Comment by laurentpellegrino** [comment]
Thank you! That resolved the issue. The deployment went smoothly :)

I've noticed that metric server pods and some other components aren’t deployed on the control nodes. I understand this setup makes sense for production. However, in a CI environment where there are no dedicated worker nodes and only auto-scaled nodes, deploying these pods on control nodes could help reduce costs. Is there a way to enable deployment on control nodes for these pods in such cases?

**Comment by M4t7e** [comment]
I think that should be doable. I would like to solve it in a generic way and I have already an idea how this could be done. Once I've completed the initial Longhorn setup, I'll start on the implementation.

**Comment by laurentpellegrino** [comment]
Fantastic! I’m excited to dive into the Longhorn support documentation. It’s impressive—everything is so well-organized, and the configuration is incredibly clean. The code structure is top-notch, too. I’ll definitely be spreading the word about this project wherever I can!

**Comment by mgerasimchuk** [comment]
I faced the same problem after I failed the first deployment attempt by my mistake.
So, when you want to make the 2nd deployment attempt from scratch don't forget to remove the artifacts of the first attempt, specifically:
- In your tf project directory:
  - terraform.tfstate
- In your Hetzner cloud:
  - Servers
  - Servers -> Snapshots
  - Servers -> Placement Groups
  - Servers -> Primary IPs
  - Networks
  - Firewalls
  - Security -> SSH Keys
  - Security -> Certificates
  
*Only after ensuring that all artifacts have been deleted, the "name is already used" error disappeared for me, and the installation was finished successfully

PS:\
@M4t7e Thank you for the great module, I used Rancher before, but your tf solution is extremely better!
PPS:\
You must add the article to https://community.hetzner.com/tutorials, cos now there are only k3s+tf/Rancher tutorials, it was not easy to find your solution, but it's really great!

**Comment by M4t7e** [comment]
@mgerasimchuk: Thank you very much! Glad you like it :slightly_smiling_face: 

> You must add the article to https://community.hetzner.com/tutorials, cos now there are only k3s+tf/Rancher tutorials, it was not easy to find your solution, but it's really great!

I’ve already thought about that. Once I’ve finished all the basics in this module, I’ll write an article and share it there!

**Comment by M4t7e** [comment]
> in a CI environment where there are no dedicated worker nodes and only auto-scaled nodes, deploying these pods on control nodes could help reduce costs. Is there a way to enable deployment on control nodes for these pods in such cases?

@lpellegr With the latest release, Cert Manager is deployed by default on Control Plane nodes. The Metrics Server is is still deployed on Worker nodes by default, unless none are configured, in which case it defaults to Control Plane nodes. You can also enforce its deployment on Control Plane nodes using the `metrics_server_schedule_on_control_plane` variable even when Worker nodes are present.

Additionally all Helm values for components can now be overridden with custom values, providing maximum flexibility for customization beyond the module's default and available settings. The relevant variables have this pattern: `<component>_helm_values`

**Comment by laurentpellegrino** [comment]
@M4t7e Great. Thanks a lot!
