### ISSUE TITLE
Enable workers on control plane nodes

### ISSUE THREAD

**Issue by lpellegr** [hcloud-k8s/terraform-hcloud-kubernetes#8]
Besides having a way to schedule metric pods on control nodes, as we discussed recently, it would also be helpful to have an option to enable worker nodes on the control plane for development purposes.

https://www.talos.dev/v1.8/talos-guides/howto/workers-on-controlplane/

**Comment by M4t7e** [comment]
That's automatically set when no worker and no autoscaler nodes are configured.
https://github.com/hcloud-k8s/terraform-hcloud-kubernetes/blob/d79a7905ae83fd162a032f0603d54fb49c8ea12e/talos_config.tf#L2

Does that already align with your use case?

**Comment by laurentpellegrino** [comment]
Ha ha ha, yes. I was deploying a new cluster to test just after creating this issue. I confirm pods can be scheduled on control nodes. The more I use this project, the more I love it :)

Sorry for the noise.

**Comment by M4t7e** [comment]
That makes me really happy to hear! :)
